auth:
  white-url-list: /login,/temp,/login*
  token-name: token
  token-prefix: every
  globalShare: false
  allow-sample-device-login: false
server:
  port: 8080
spring:
  redis:
    url: redis://root:e9xkcVZIGY3A6RoP@159.75.122.3:6379
