auth:
  white-url-list: /login,/temp
  token-name: token
  token-prefix: every
  read-from: url
  globalShare: true
server:
  port: 8080
spring:
  redis:
    url: redis://root:e9xkcVZIGY3A6RoP@159.75.122.3:6379
